### PR TITLE
Update for changes in vfile, remark

### PR DESCRIPTION
**Pull request by wooorm**
Hi! 👋

I’ve just upped remark (which includes a new vfile).
Please review, merge, and release major at your leisure. Or, if you’d like, donate this project to the [vfile organisation](https://github.com/vfile) and I’ll take care of it!

P.S. I’ll work on [vfile-reporter-pretty](https://github.com/sindresorhus/vfile-reporter-pretty) after this is released.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Or, if you’d like, donate this project to the vfile organisation and I’ll take care of it!

Sure. Add me to the org and I'll transfer over this and the pretty formatter.

**Comment by wooorm** [comment]
Done! 👍

**Comment by sindresorhus** [comment]
Done too ;)

**Comment by wooorm** [comment]
Perfect, released as 1.0.0!

**Pull request merged**
